name = "FerriteBifurcationKit"
uuid = "813f8696-2795-4669-aca4-b56c4084c5bd"
authors = ["Aminofa70 <amin.alibakhshi@upm.es> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
